version: '3.4'

volumes:
  timelin_postgres:
    external: true
    
networks:
  traefik:
    external: true

services:
  api:
    depends_on:
      - database
      - pushpin
    image: modalnodes/images:timelin_0.0.31
    networks:
      - traefik
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == bender
      labels:
        - "traefik.docker.network=traefik"
        - "traefik.frontend.rule=Host:api.timel.in"
        - "traefik.port=80"
    environment:
      DB_ENGINE: ${MN_DB_ENGINE}
      DB_HOST: database
      DB_NAME: ${MN_DB_NAME}
      DB_USER: ${MN_DB_USER}
      DB_PASS: ${MN_DB_PASSWORD}      
  
  database:
    image: mdillon/postgis:latest
    volumes:
      - timelin_postgres:/var/lib/postgresql/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == bender
    environment:
      POSTGRES_PASSWORD: ${MN_DB_PASSWORD}
      POSTGRES_USER: ${MN_DB_USER}
      POSTGRES_DB: ${MN_DB_NAME}
      
